project_id = "twqmjbnhpcuecggueszi"

[functions.send-whatsapp]
verify_jwt = false

[functions.send-contact-whatsapp]
verify_jwt = false

[functions.send-appointment-confirmation]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.csp-headers]
verify_jwt = false
